"""Coherent resolution of the maintained Lubko command line tools.

The global entry points (``lubko-agent``, ``lubko-worker``, ``lubko-deploy``,
``lubko-deploy-ctl``, ``lubko-install``, and ``my-lubko-agent``) must always
resolve to code from the *confirmed* maintained commit. A supervised
deployment checks out a provisional candidate and may roll back to the
previous commit at any time before confirmation, so the global CLIs must never
be stranded on candidate code.

This module keeps the CLIs coherent with a stable indirection instead of
rewriting an installed ``uv`` tool in place:

- every global entry point is a small stable launcher script, written once by
  ``lubko-install`` and never rewritten by a deployment;
- each commit owns an immutable per-commit CLI environment under
  ``$XDG_STATE_HOME/lubko/cli/<commit>/``: a plain ``git archive`` extraction
  of the exact commit tree plus the virtualenv ``uv sync`` creates there;
- ``$XDG_STATE_HOME/lubko/cli/current`` is a symlink selecting the active
  commit and is switched with a single atomic ``os.replace``.

Deployments build the candidate environment during the provisional phase and
only move ``current`` after durable ``confirmed`` state exists. A rollback
therefore never needs to restore the CLIs: the pointer was never moved, so the
prior confirmed CLI version is preserved by construction.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from contextlib import suppress
from pathlib import Path
from typing import TYPE_CHECKING, Final

from lubko.state import cli_root_dir, state_root

if TYPE_CHECKING:
    from collections.abc import Sequence

ENTRY_POINTS: Final = (
    "lubko-agent",
    "lubko-worker",
    "lubko-deploy",
    "lubko-deploy-ctl",
    "lubko-install",
    "my-lubko-agent",
)
CURRENT_LINK_NAME: Final = "current"
CURRENT_TMP_NAME: Final = "current.tmp"
DEFAULT_BUILD_TIMEOUT_SECONDS: Final = 600.0
UV_HTTP_TIMEOUT: Final = "30"

_LAUNCHER_TEMPLATE: Final = """#!/bin/sh
# Stable Lubko launcher (generated by lubko-install). Deployments never rewrite
# this file; they only switch the `current` symlink that this script resolves.
set -u
LINK='{state_root}/cli/current'
ENTRY='{entry}'
if [ ! -L "$LINK" ]; then
  printf '%s: no maintained Lubko CLI; run lubko-install\\n' "$ENTRY" >&2
  exit 1
fi
BASE="$(dirname "$LINK")"
TARGET="$(readlink "$LINK")" || exit 1
case "$TARGET" in
  /*) REL="$TARGET" ;;
  *) REL="$BASE/$TARGET" ;;
esac
ROOT="$(cd "$REL" 2>/dev/null && pwd -P)" || {{
  printf '%s: maintained CLI root %s missing; reinstall\\n' "$ENTRY" "$REL" >&2
  exit 1
}}
BIN="$ROOT/.venv/bin/$ENTRY"
if [ ! -x "$BIN" ]; then
  printf '%s: incomplete CLI root (%s); reinstall\\n' "$ENTRY" "$BIN" >&2
  exit 1
fi
exec "$BIN" "$@"
"""


class CliError(RuntimeError):
    """Raised when a maintained CLI environment cannot be built or switched."""


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def cli_commit_dir(commit: str) -> Path:
    """Return the immutable CLI environment directory of one commit.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        The per-commit CLI root.
    """
    return cli_root_dir() / commit


def current_link_path() -> Path:
    """Return the symlink selecting the active maintained CLI commit.

    Returns:
        The ``current`` symlink path.
    """
    return cli_root_dir() / CURRENT_LINK_NAME


def current_commit() -> str | None:
    """Return the commit the maintained CLIs currently resolve to.

    Returns:
        The active commit, or ``None`` when no maintained CLI is active.
    """
    try:
        target = current_link_path().readlink()
    except OSError:
        return None
    return Path(target).name


def cli_entry_executable(commit: str, entry: str) -> Path | None:
    """Return the executable for an entry point within one commit root.

    Args:
        commit: Exact commit hash.
        entry: Maintained entry point name.

    Returns:
        The virtualenv entry-point script, or ``None`` when it is absent.
    """
    executable = cli_commit_dir(commit) / ".venv" / "bin" / entry
    if executable.is_file():
        return executable
    return None


def _root_is_usable(commit: str) -> bool:
    """Return whether a commit's CLI environment looks fully built.

    Args:
        commit: Exact commit hash.

    Returns:
        ``True`` when the per-commit environment exists with its entry points.
    """
    return cli_entry_executable(commit, "lubko-agent") is not None


# ---------------------------------------------------------------------------
# Build and activation
# ---------------------------------------------------------------------------


def _extract_archive(repo: Path, commit: str, destination: Path, timeout_seconds: float) -> None:
    """Extract the exact tree of a commit into a directory.

    Args:
        repo: Repository checkout that contains the commit.
        commit: Exact commit hash to extract.
        destination: Directory to receive the extracted tree.
        timeout_seconds: Bounded timeout.

    Raises:
        CliError: If the archive or extraction fails.
    """
    try:
        archived = subprocess.run(
            ["git", "-C", str(repo), "archive", commit],
            capture_output=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not archive commit {commit}: {exc}"
        raise CliError(msg) from exc
    if archived.returncode != 0:
        detail = (
            archived.stderr or archived.stdout
        ).decode().strip() or f"exit code {archived.returncode}"
        msg = f"git archive of commit {commit} failed: {detail}"
        raise CliError(msg)
    try:
        extracted = subprocess.run(
            ["tar", "-x", "-C", str(destination)],
            input=archived.stdout,
            capture_output=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not extract commit {commit}: {exc}"
        raise CliError(msg) from exc
    if extracted.returncode != 0:
        detail = (
            extracted.stderr or extracted.stdout
        ).decode().strip() or f"exit code {extracted.returncode}"
        msg = f"extraction of commit {commit} failed: {detail}"
        raise CliError(msg)


def _sync_venv(uv_path: str, root: Path, timeout_seconds: float) -> None:
    """Synchronize the virtualenv of one extracted commit tree.

    Args:
        uv_path: Path to the ``uv`` executable.
        root: Extracted commit tree.
        timeout_seconds: Bounded timeout.

    Raises:
        CliError: If ``uv sync`` fails.
    """
    env = dict(os.environ)
    env.setdefault("UV_HTTP_TIMEOUT", UV_HTTP_TIMEOUT)
    try:
        proc = subprocess.run(
            [uv_path, "sync", "--project", str(root)],
            cwd=root,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not synchronize the CLI environment: {exc}"
        raise CliError(msg) from exc
    if proc.returncode != 0:
        lines = [line for line in (proc.stderr or proc.stdout).splitlines() if line]
        detail = "\n".join(lines[-10:]) or f"exit code {proc.returncode}"
        msg = f"uv sync for the CLI environment failed:\n{detail}"
        raise CliError(msg)


def build_cli_root(repo: Path, commit: str, uv_path: str, timeout_seconds: float) -> Path:
    """Build or reuse the immutable CLI environment for one exact commit.

    The environment is extracted with ``git archive`` and synchronized with
    ``uv sync`` directly at its final location, so entry-point shebangs stay
    valid. Building the same commit twice is idempotent and never rewrites an
    already-usable environment.

    Args:
        repo: Repository checkout that contains the commit.
        commit: Exact commit hash.
        uv_path: Path to the ``uv`` executable.
        timeout_seconds: Bounded timeout per step.

    Returns:
        The commit's CLI environment directory.

    Raises:
        CliError: If the environment cannot be built.
    """
    destination = cli_commit_dir(commit)
    if _root_is_usable(commit):
        return destination
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)
    try:
        _extract_archive(repo, commit, destination, timeout_seconds)
        _sync_venv(uv_path, destination, timeout_seconds)
    except CliError:
        shutil.rmtree(destination, ignore_errors=True)
        raise
    if not _root_is_usable(commit):
        shutil.rmtree(destination, ignore_errors=True)
        msg = f"CLI environment for commit {commit} is incomplete after build"
        raise CliError(msg)
    return destination


def set_current(commit: str) -> None:
    """Atomically select the commit the maintained CLIs resolve to.

    Args:
        commit: Exact commit hash to activate.

    Raises:
        CliError: If the pointer cannot be switched.
    """
    directory = cli_root_dir()
    directory.mkdir(parents=True, exist_ok=True)
    temporary = directory / CURRENT_TMP_NAME
    try:
        temporary.symlink_to(commit)
        temporary.replace(current_link_path())
    except OSError as exc:
        with suppress(OSError):
            temporary.unlink()
        msg = f"could not activate CLI commit {commit}: {exc}"
        raise CliError(msg) from exc


def remove_cli_root(commit: str) -> None:
    """Remove one commit's CLI environment if it is not the active one.

    Args:
        commit: Exact commit hash to remove.
    """
    if commit == current_commit():
        return
    shutil.rmtree(cli_commit_dir(commit), ignore_errors=True)


def gc_cli_roots(keep: Sequence[str]) -> None:
    """Remove every CLI environment except the commits listed.

    The ``current`` symlink itself is never removed.

    Args:
        keep: Commits whose environments must be retained.
    """
    keep_set = set(keep)
    for path in cli_root_dir().iterdir() if cli_root_dir().is_dir() else ():
        if path.name in {CURRENT_LINK_NAME, CURRENT_TMP_NAME}:
            continue
        if path.name not in keep_set:
            shutil.rmtree(path, ignore_errors=True)


# ---------------------------------------------------------------------------
# Launchers
# ---------------------------------------------------------------------------


def launcher_source(entry: str) -> str:
    """Return the stable shell launcher text for one maintained entry point.

    Args:
        entry: Maintained entry point name.

    Returns:
        Executable shell script resolving the active CLI commit.
    """
    return _LAUNCHER_TEMPLATE.format(state_root=state_root(), entry=entry)


def install_launchers(bin_dir: Path) -> None:
    """Write every stable launcher into a bin directory.

    Each launcher is written atomically and never changed by deployments.

    Args:
        bin_dir: Directory to install the launchers into.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    for entry in ENTRY_POINTS:
        target = bin_dir / entry
        temporary = bin_dir / f"{entry}.tmp"
        temporary.write_text(launcher_source(entry), encoding="utf-8")
        temporary.chmod(0o755)
        temporary.replace(target)


def git_commit(repo: Path, timeout_seconds: float) -> str | None:
    """Return the full git commit of a checkout, read-only.

    Args:
        repo: Repository checkout to inspect.
        timeout_seconds: Bounded timeout.

    Returns:
        The full commit hash, or ``None`` when unavailable.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    commit = proc.stdout.strip()
    return commit or None
