"""Coherent resolution of the maintained Lubko command line tools.

The global entry points (``lubko-agent``, ``lubko-worker``, ``lubko-deploy``,
``lubko-deploy-ctl``, ``lubko-install``, and ``my-lubko-agent``) must always
resolve to code from the *confirmed* maintained commit. A supervised
deployment checks out a provisional candidate and may roll back to the
previous commit at any time before confirmation, so the global CLIs must never
be stranded on candidate code.

This module keeps the CLIs coherent with a stable indirection instead of
rewriting an installed ``uv`` tool in place:

- every global entry point is a small stable launcher script, written once by
  ``lubko-install`` and never rewritten by a deployment;
- each commit owns an immutable per-commit CLI environment under
  ``$XDG_STATE_HOME/lubko/cli/<commit>/``: a plain ``git archive`` extraction
  of the exact commit tree plus the virtualenv ``uv sync`` creates there; at
  materialization it is bound to the exact full commit by a manifest carrying
  a deterministic content digest, then ``sealed`` read-only — sealing never
  rewrites that identity, so normal operation never writes to it and a
  modified/re-sealed tree is never trusted;
- ``$XDG_STATE_HOME/lubko/cli/current`` is a symlink selecting the active
  commit and is switched with a single atomic ``os.replace``.

Deployments build the candidate environment during the provisional phase and
only move ``current`` after durable ``confirmed`` state exists. A rollback
therefore never needs to restore the CLIs: the pointer was never moved, so the
prior confirmed CLI version is preserved by construction.

A sealed runtime is only ever made writable again (``unseal_runtime``) for an
explicit rebuild/removal/GC operation; it is never unsealed during ordinary
start, restart, probe, or crash recovery.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import shutil
import stat
import subprocess
from contextlib import suppress
from operator import itemgetter
from pathlib import Path
from typing import TYPE_CHECKING, Final

from lubko.state import cli_root_dir, state_root
from lubko.supervise import read_supervisor_runtime_override

if TYPE_CHECKING:
    from collections.abc import Sequence

ENTRY_POINTS: Final = (
    "lubko-agent",
    "lubko-worker",
    "lubko-supervisor",
    "lubko-deploy",
    "lubko-deploy-ctl",
    "lubko-install",
    "my-lubko-agent",
)
CURRENT_LINK_NAME: Final = "current"
CURRENT_TMP_NAME: Final = "current.tmp"
DEFAULT_BUILD_TIMEOUT_SECONDS: Final = 600.0
UV_HTTP_TIMEOUT: Final = "30"

RUNTIME_MANIFEST_NAME: Final = "lubko-runtime.json"
RUNTIME_MANIFEST_SCHEMA: Final = 2
COMMIT_PATH_RE: Final = re.compile(r"[0-9a-fA-F]{40}")

_WRITE_BITS: Final = stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH

_LAUNCHER_TEMPLATE: Final = """#!/bin/sh
# Stable Lubko launcher (generated by lubko-install). Deployments never rewrite
# this file; they only switch the `current` symlink that this script resolves.
set -u
LINK='{state_root}/cli/current'
ENTRY='{entry}'
if [ ! -L "$LINK" ]; then
  printf '%s: no maintained Lubko CLI; run lubko-install\\n' "$ENTRY" >&2
  exit 1
fi
BASE="$(dirname "$LINK")"
TARGET="$(readlink "$LINK")" || exit 1
case "$TARGET" in
  /*) REL="$TARGET" ;;
  *) REL="$BASE/$TARGET" ;;
esac
ROOT="$(cd "$REL" 2>/dev/null && pwd -P)" || {{
  printf '%s: maintained CLI root %s missing; reinstall\\n' "$ENTRY" "$REL" >&2
  exit 1
}}
BIN="$ROOT/.venv/bin/$ENTRY"
if [ ! -x "$BIN" ]; then
  printf '%s: incomplete CLI root (%s); reinstall\\n' "$ENTRY" "$BIN" >&2
  exit 1
fi
exec "$BIN" "$@"
"""


class CliError(RuntimeError):
    """Raised when a maintained CLI environment cannot be built or switched."""


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def is_valid_commit_name(name: str) -> bool:
    """Return whether ``name`` is exactly 40 hexadecimal characters.

    Runtime directories are addressed by the full commit SHA alone; a short
    ref, a relative path, or any non-hex value must never resolve to a runtime
    path.

    Args:
        name: Candidate commit name.

    Returns:
        ``True`` when the name is exactly 40 hex characters.
    """
    return COMMIT_PATH_RE.fullmatch(name) is not None


def validate_commit_name(commit: str) -> None:
    """Require ``commit`` to be exactly 40 hexadecimal characters.

    Args:
        commit: Exact commit hash.

    Raises:
        CliError: If the value is not a full 40-hex-character commit.
    """
    if not is_valid_commit_name(commit):
        msg = "runtime commits must be exactly 40 hexadecimal characters"
        raise CliError(msg)


def cli_commit_dir(commit: str) -> Path:
    """Return the immutable CLI environment directory of one commit.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        The per-commit CLI root.
    """
    validate_commit_name(commit)
    return cli_root_dir() / commit


def current_link_path() -> Path:
    """Return the symlink selecting the active maintained CLI commit.

    Returns:
        The ``current`` symlink path.
    """
    return cli_root_dir() / CURRENT_LINK_NAME


def current_commit() -> str | None:
    """Return the commit the maintained CLIs currently resolve to.

    Returns:
        The active commit, or ``None`` when no maintained CLI is active.
    """
    try:
        target = current_link_path().readlink()
    except OSError:
        return None
    return Path(target).name


def cli_entry_executable(commit: str, entry: str) -> Path | None:
    """Return the executable for an entry point within one commit root.

    Args:
        commit: Exact commit hash.
        entry: Maintained entry point name.

    Returns:
        The virtualenv entry-point script, or ``None`` when it is absent.
    """
    executable = cli_commit_dir(commit) / ".venv" / "bin" / entry
    if executable.is_file():
        return executable
    return None


def _root_is_usable(commit: str) -> bool:
    """Return whether a commit's CLI environment looks fully built.

    Every maintained entry point must exist: older commits may predate one of
    the seven entry points, and activating such a root would leave that global
    command broken.

    Args:
        commit: Exact commit hash.

    Returns:
        ``True`` when the per-commit environment has every entry point.
    """
    return all(cli_entry_executable(commit, entry) is not None for entry in ENTRY_POINTS)


def manifest_path(commit: str) -> Path:
    """Return the binding-manifest path of one commit runtime.

    The manifest binds the materialized tree to the exact full commit, the
    runtime schema, and a deterministic content digest of the sealed tree so a
    stale, wrong-commit, partially built, or tampered tree can never be
    mistaken for the exact deployed runtime.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        The ``lubko-runtime.json`` path inside the commit runtime.
    """
    return cli_commit_dir(commit) / RUNTIME_MANIFEST_NAME


def _lstat_mode(path: Path) -> int | None:
    """Return the mode of a path without following a trailing symlink.

    Args:
        path: Path to inspect.

    Returns:
        The link-safe mode bits, or ``None`` when the entry is gone/unreadable.
    """
    try:
        return path.lstat().st_mode
    except OSError:
        return None


def _seal_tree(root: Path) -> None:
    """Remove every write bit below ``root`` so normal operation cannot modify it.

    Symlinks are never chmodded: mutating a symlink's mode bits would follow
    the link and alter an external target. Only regular files and directories
    are sealed.

    Args:
        root: Runtime tree to make read-only.
    """
    for dirpath, dirnames, filenames in os.walk(root):
        for name in (*dirnames, *filenames):
            with suppress(OSError):
                path = Path(dirpath) / name
                mode = path.lstat().st_mode
                if not stat.S_ISLNK(mode):
                    path.chmod(mode & ~_WRITE_BITS)
        with suppress(OSError):
            directory = Path(dirpath)
            mode = directory.lstat().st_mode
            if not stat.S_ISLNK(mode):
                directory.chmod(mode & ~_WRITE_BITS)


def _unseal_tree(root: Path) -> None:
    """Restore owner-write permission below ``root`` for a rebuild/removal/GC.

    Symlinks are deliberately skipped: only regular files and directories are
    made writable, so an external symlink target retains its own mode.

    Args:
        root: Runtime tree to make writable again.
    """
    for dirpath, dirnames, filenames in os.walk(root):
        for name in (*dirnames, *filenames):
            with suppress(OSError):
                path = Path(dirpath) / name
                mode = path.lstat().st_mode
                if not stat.S_ISLNK(mode):
                    path.chmod(mode | stat.S_IWUSR)
        with suppress(OSError):
            directory = Path(dirpath)
            mode = directory.lstat().st_mode
            if not stat.S_ISLNK(mode):
                directory.chmod(mode | stat.S_IWUSR)


def _tree_is_read_only(root: Path) -> bool:
    """Return whether every entry below ``root`` is free of write bits.

    Symlinks are inspected with ``lstat`` and excluded from the write-bit
    rule: their mode bits cannot escape the sealed runtime because sealing
    never follows a symlink, and ``os.walk`` does not descend into symlinked
    directories.

    Args:
        root: Runtime tree to verify.

    Returns:
        ``True`` when no regular file or directory under ``root`` is writable.
    """
    if not root.is_dir():
        return False
    for dirpath, dirnames, filenames in os.walk(root):
        for name in (*dirnames, *filenames):
            mode = _lstat_mode(Path(dirpath) / name)
            if mode is None:
                return False
            if stat.S_ISLNK(mode):
                continue
            if mode & _WRITE_BITS:
                return False
        mode = _lstat_mode(Path(dirpath))
        if mode is None or mode & _WRITE_BITS:
            return False
    return True


def _file_content_digest(path: Path) -> bytes:
    """Return the raw SHA-256 of one regular file's contents.

    Args:
        path: Regular file to digest.

    Returns:
        The 32 raw digest bytes.
    """
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                return hasher.digest()
            hasher.update(chunk)


def _runtime_content_digest(root: Path) -> bytes:
    """Return the deterministic content digest of one runtime tree.

    The digest binds every entry below ``root`` except the binding manifest
    itself: regular files contribute their relative path, permission mode
    (write bits masked so sealing order never matters), and a content digest;
    symlinks contribute their relative path and exact link target without ever
    following the link; directories and any other entry type contribute their
    relative path (and mode where meaningful). Each contribution is
    length-prefixed, so added, removed, renamed, or tampered entries always
    change the digest.

    Args:
        root: Runtime tree to digest.

    Returns:
        The raw SHA-256 digest bytes over the canonical tree encoding.
    """
    entries: list[tuple[str, Path, os.stat_result]] = []

    def collect(directory: Path) -> None:
        with os.scandir(directory) as iterator:
            for entry in iterator:
                path = Path(entry.path)
                rel = path.relative_to(root).as_posix()
                if rel == RUNTIME_MANIFEST_NAME:
                    continue
                info = path.lstat()
                entries.append((rel, path, info))
                if stat.S_ISDIR(info.st_mode):
                    collect(path)

    collect(root)
    hasher = hashlib.sha256()

    def update(data: bytes) -> None:
        hasher.update(len(data).to_bytes(8, "big"))
        hasher.update(data)

    for rel, path, info in sorted(entries, key=itemgetter(0)):
        update(rel.encode("utf-8"))
        if stat.S_ISREG(info.st_mode):
            update(b"f")
            update((info.st_mode & ~_WRITE_BITS & 0o777).to_bytes(2, "big"))
            update(_file_content_digest(path))
        elif stat.S_ISLNK(info.st_mode):
            update(b"l")
            update(os.fspath(path.readlink()).encode("utf-8"))
        elif stat.S_ISDIR(info.st_mode):
            update(b"d")
        else:
            update(b"o")
            update((info.st_mode & ~_WRITE_BITS & 0o777).to_bytes(2, "big"))
    return hasher.digest()


def _write_runtime_manifest(commit: str) -> None:
    """Bind one materialized runtime to its exact commit with a content digest.

    The expected identity of a commit runtime is established exactly once, at
    materialization time, from the tree just extracted from the exact commit
    (``git archive`` plus ``uv sync``). Sealing later only changes permissions
    and never rewrites this manifest, so a tree modified after materialization
    can never be re-blessed while still claiming ``commit``.

    Args:
        commit: Exact 40-character commit hash.

    Raises:
        CliError: If the runtime tree cannot be digested.
    """
    root = cli_commit_dir(commit)
    try:
        content_digest = _runtime_content_digest(root).hex()
    except OSError as exc:
        msg = f"could not digest the runtime tree for commit {commit}: {exc}"
        raise CliError(msg) from exc
    manifest = {
        "schema_version": RUNTIME_MANIFEST_SCHEMA,
        "commit": commit,
        "content_digest": content_digest,
    }
    manifest_path(commit).write_text(json.dumps(manifest, sort_keys=True) + "\n", encoding="utf-8")


def seal_runtime(commit: str) -> None:
    """Seal one materialized commit runtime read-only.

    Only permission bits below the runtime tree are removed: the integrity
    manifest is written at materialization time and is never rewritten here, so
    a later unseal/reseal cannot redefine the commit-bound expected identity.
    Normal operation (start, restart, probe, crash recovery) must only ever use
    a sealed runtime whose manifest is verified. Symlinks in the tree are never
    followed or chmodded.

    Args:
        commit: Exact 40-character commit hash to seal.
    """
    validate_commit_name(commit)
    root = cli_commit_dir(commit)
    if not root.is_dir():
        return
    _seal_tree(root)


def unseal_runtime(commit: str) -> None:
    """Make a sealed commit runtime writable for an explicit rebuild/removal/GC.

    This is the deliberate, supported exception to read-only operation. It is
    only invoked by operations that repair or remove the tree; ordinary
    supervised start/restart never unseals. Symlinks in the tree are never
    followed or chmodded.

    Args:
        commit: Exact 40-character commit hash to unseal.
    """
    validate_commit_name(commit)
    root = cli_commit_dir(commit)
    if root.is_dir():
        _unseal_tree(root)


def _manifest_digest(data: object, commit: str) -> bytes | None:
    """Return the tree digest recorded by a manifest when it binds ``commit``.

    Args:
        data: Parsed manifest document.
        commit: Exact commit the manifest must bind.

    Returns:
        The recorded content-digest bytes, or ``None`` when the manifest does
        not bind ``commit`` under the current schema or carries no valid digest.
    """
    if not (
        isinstance(data, dict)
        and data.get("schema_version") == RUNTIME_MANIFEST_SCHEMA
        and data.get("commit") == commit
    ):
        return None
    expected = data.get("content_digest")
    if not isinstance(expected, str):
        return None
    try:
        return bytes.fromhex(expected)
    except ValueError:
        return None


def runtime_is_usable(commit: str) -> bool:
    """Return whether a commit runtime is complete, exactly bound, and sealed.

    An unsealed, incomplete, wrong-commit, corrupt, or content-tampered tree is
    deliberately reported unusable so callers fail closed instead of launching
    arbitrary mutable code. The manifest's ``content_digest`` is recomputed over
    the current tree on every call, so a runtime that was unsealed, modified,
    and re-sealed without regenerating the manifest is rejected. An invalid
    commit name is never usable.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        ``True`` only when every entry point exists, the manifest binds the
        tree to ``commit`` under the current schema, the tree is read-only, and
        the recomputed tree digest matches the manifest.
    """
    if not is_valid_commit_name(commit) or not _root_is_usable(commit):
        return False
    try:
        data = json.loads(manifest_path(commit).read_text())
    except (OSError, ValueError):
        return False
    expected = _manifest_digest(data, commit)
    if expected is None:
        return False
    root = cli_commit_dir(commit)
    if not _tree_is_read_only(root):
        return False
    try:
        return _runtime_content_digest(root) == expected
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Build and activation
# ---------------------------------------------------------------------------


def _extract_archive(repo: Path, commit: str, destination: Path, timeout_seconds: float) -> None:
    """Extract the exact tree of a commit into a directory.

    Args:
        repo: Repository checkout that contains the commit.
        commit: Exact commit hash to extract.
        destination: Directory to receive the extracted tree.
        timeout_seconds: Bounded timeout.

    Raises:
        CliError: If the archive or extraction fails.
    """
    try:
        archived = subprocess.run(
            ["git", "-C", str(repo), "archive", commit],
            capture_output=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not archive commit {commit}: {exc}"
        raise CliError(msg) from exc
    if archived.returncode != 0:
        detail = (
            archived.stderr or archived.stdout
        ).decode().strip() or f"exit code {archived.returncode}"
        msg = f"git archive of commit {commit} failed: {detail}"
        raise CliError(msg)
    try:
        extracted = subprocess.run(
            ["tar", "-x", "-C", str(destination)],
            input=archived.stdout,
            capture_output=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not extract commit {commit}: {exc}"
        raise CliError(msg) from exc
    if extracted.returncode != 0:
        detail = (
            extracted.stderr or extracted.stdout
        ).decode().strip() or f"exit code {extracted.returncode}"
        msg = f"extraction of commit {commit} failed: {detail}"
        raise CliError(msg)


def _sync_venv(uv_path: str, root: Path, timeout_seconds: float) -> None:
    """Synchronize the virtualenv of one extracted commit tree.

    Args:
        uv_path: Path to the ``uv`` executable.
        root: Extracted commit tree.
        timeout_seconds: Bounded timeout.

    Raises:
        CliError: If ``uv sync`` fails.
    """
    env = dict(os.environ)
    env.setdefault("UV_HTTP_TIMEOUT", UV_HTTP_TIMEOUT)
    try:
        proc = subprocess.run(
            [uv_path, "sync", "--project", str(root)],
            cwd=root,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not synchronize the CLI environment: {exc}"
        raise CliError(msg) from exc
    if proc.returncode != 0:
        lines = [line for line in (proc.stderr or proc.stdout).splitlines() if line]
        detail = "\n".join(lines[-10:]) or f"exit code {proc.returncode}"
        msg = f"uv sync for the CLI environment failed:\n{detail}"
        raise CliError(msg)


def build_cli_root(repo: Path, commit: str, uv_path: str, timeout_seconds: float) -> Path:
    """Build or reuse the immutable CLI environment for one exact commit.

    The environment is extracted with ``git archive`` and synchronized with
    ``uv sync`` directly at its final location, so entry-point shebangs stay
    valid. Building the same commit twice is idempotent and never rewrites an
    already-sealed usable environment. Once materialized and verified it is
    sealed read-only; an unsealed/corrupt/wrong-commit tree is unsealed,
    removed, and rebuilt rather than trusted.

    Args:
        repo: Repository checkout that contains the commit.
        commit: Exact commit hash.
        uv_path: Path to the ``uv`` executable.
        timeout_seconds: Bounded timeout per step.

    Returns:
        The commit's sealed CLI environment directory.

    Raises:
        CliError: If the environment cannot be built or sealed.
    """
    validate_commit_name(commit)
    destination = cli_commit_dir(commit)
    if runtime_is_usable(commit):
        return destination
    unseal_runtime(commit)
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)
    try:
        _extract_archive(repo, commit, destination, timeout_seconds)
        _sync_venv(uv_path, destination, timeout_seconds)
    except CliError:
        shutil.rmtree(destination, ignore_errors=True)
        raise
    if not _root_is_usable(commit):
        shutil.rmtree(destination, ignore_errors=True)
        msg = f"CLI environment for commit {commit} is incomplete after build"
        raise CliError(msg)
    _write_runtime_manifest(commit)
    seal_runtime(commit)
    if not runtime_is_usable(commit):
        unseal_runtime(commit)
        shutil.rmtree(destination, ignore_errors=True)
        msg = f"CLI environment for commit {commit} could not be sealed"
        raise CliError(msg)
    return destination


def set_current(commit: str) -> None:
    """Atomically select the commit the maintained CLIs resolve to.

    Args:
        commit: Exact commit hash to activate.

    Raises:
        CliError: If the pointer cannot be switched or ``commit`` is invalid.
    """
    validate_commit_name(commit)
    directory = cli_root_dir()
    directory.mkdir(parents=True, exist_ok=True)
    temporary = directory / CURRENT_TMP_NAME
    try:
        temporary.symlink_to(commit)
        temporary.replace(current_link_path())
    except OSError as exc:
        with suppress(OSError):
            temporary.unlink()
        msg = f"could not activate CLI commit {commit}: {exc}"
        raise CliError(msg) from exc


def reconcile_pointer(commit: str) -> bool:
    """Idempotently repair the active pointer so it selects one commit.

    The switch happens only when the commit's environment is already sealed and
    usable, so a repair never activates an incomplete, unsealed, corrupt, or
    wrong-commit root and never touches a provisional candidate that is not
    yet the confirmed commit. An already-current pointer is only blessed when
    the runtime it points to is itself usable.

    Args:
        commit: Exact commit hash the pointer should select.

    Returns:
        ``True`` when the pointer now selects a usable runtime (there was
        nothing to repair, or the repair succeeded), ``False`` when the
        runtime is missing, unusable, invalid, or the pointer could not be
        switched.
    """
    if not runtime_is_usable(commit):
        return False
    if current_commit() == commit:
        return True
    try:
        set_current(commit)
    except CliError:
        return False
    return True


def remove_cli_root(commit: str) -> None:
    """Remove one commit's CLI environment if it is not the active one.

    A sealed runtime is unsealed first so the explicit removal actually works.
    An invalid commit name is never removed (fail closed).

    Args:
        commit: Exact commit hash to remove.
    """
    if not is_valid_commit_name(commit) or commit == current_commit():
        return
    root = cli_commit_dir(commit)
    if not root.exists():
        return
    unseal_runtime(commit)
    shutil.rmtree(root, ignore_errors=True)


def gc_cli_roots(keep: Sequence[str]) -> None:
    """Remove every CLI environment except the commits listed.

    The environment selected by the ``current`` symlink is always preserved,
    even when it is absent from ``keep``. Activation may have failed after
    durable state was written, so a cleanup must never delete the root that the
    global CLIs currently resolve to.  The supervisor-runtime override commit
    (when staged by ``lubko-deploy bootstrap``) is also preserved so the
    override remains usable across GC passes.  Sealed environments are unsealed
    first so the explicit GC actually removes them; commit-addressed paths are
    validated before any unseal.

    Args:
        keep: Commits whose environments must be retained.
    """
    keep_set = set(keep)
    current = current_commit()
    if current is not None:
        keep_set.add(current)
    override = read_supervisor_runtime_override()
    if override is not None:
        keep_set.add(override)
    for path in cli_root_dir().iterdir() if cli_root_dir().is_dir() else ():
        if path.name in {CURRENT_LINK_NAME, CURRENT_TMP_NAME}:
            continue
        if path.name not in keep_set:
            if is_valid_commit_name(path.name):
                unseal_runtime(path.name)
            shutil.rmtree(path, ignore_errors=True)


# ---------------------------------------------------------------------------
# Launchers
# ---------------------------------------------------------------------------


SUPERVISOR_ENTRY: Final = "lubko-supervisor"
_SUPERVISOR_STATE_ROOT_PLACEHOLDER: Final = "@@LUBKO_STATE_ROOT@@"

_SUPERVISOR_LAUNCHER_TEMPLATE: Final = """#!/bin/sh
# Stable lubko-supervisor launcher (generated by lubko-install).
# Deployments never rewrite this file; they only switch the `current` symlink
# or publish a supervisor-runtime override that this script resolves.
#
# The override is a plain text file containing exactly one 40-hex commit plus
# newline.  When present and valid the supervisor daemon runs from that
# commit's sealed runtime instead of cli/current.  A corrupt or incomplete
# override fails closed: the launcher refuses to start rather than silently
# falling back to an unintended runtime.
set -u
ENTRY='lubko-supervisor'
STATE='@@LUBKO_STATE_ROOT@@'
OVERRIDE="$STATE/supervisor/supervisor-runtime"
LINK="$STATE/cli/current"

# --- resolve override or fall back to cli/current ---
if [ -f "$OVERRIDE" ]; then
  # Portable size gate: exactly 41 bytes (40 hex + newline).
  _OVERRIDE_SIZE="$(wc -c < "$OVERRIDE" 2>/dev/null)" || {
    printf '%s: could not read supervisor-runtime override size\\n' "$ENTRY" >&2
    exit 1
  }
  case "$_OVERRIDE_SIZE" in
    41) ;;
    *)
      printf '%s: supervisor-runtime override is not a valid 40-hex commit\\n' \\
        "$ENTRY" >&2
      exit 1
      ;;
  esac
  COMMIT="$(cat "$OVERRIDE")" || {
    printf '%s: could not read supervisor-runtime override\\n' "$ENTRY" >&2
    exit 1
  }
  # strict validation: exactly 40 lowercase hex chars, nothing else
  case "$COMMIT" in
    [0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f])
      ;;
    *)
      printf '%s: supervisor-runtime override is not a valid 40-hex commit\\n' \\
        "$ENTRY" >&2
      exit 1
      ;;
  esac
  ROOT="$STATE/cli/$COMMIT"
  if [ ! -d "$ROOT" ]; then
    printf '%s: supervisor-runtime override commit %s has no runtime dir\\n' \\
      "$ENTRY" "$COMMIT" >&2
    exit 1
  fi
  BIN="$ROOT/.venv/bin/$ENTRY"
  if [ ! -x "$BIN" ]; then
    printf '%s: supervisor-runtime override commit %s is incomplete\\n' \\
      "$ENTRY" "$COMMIT" >&2
    exit 1
  fi
  exec "$BIN" "$@"
fi

# --- no override: resolve through cli/current (normal path) ---
if [ ! -L "$LINK" ]; then
  printf '%s: no maintained Lubko CLI; run lubko-install\\n' "$ENTRY" >&2
  exit 1
fi
BASE="$(dirname "$LINK")"
TARGET="$(readlink "$LINK")" || exit 1
case "$TARGET" in
  /*) REL="$TARGET" ;;
  *) REL="$BASE/$TARGET" ;;
esac
ROOT="$(cd "$REL" 2>/dev/null && pwd -P)" || {
  printf '%s: maintained CLI root %s missing; reinstall\\n' "$ENTRY" "$REL" >&2
  exit 1
}
BIN="$ROOT/.venv/bin/$ENTRY"
if [ ! -x "$BIN" ]; then
  printf '%s: incomplete CLI root (%s); reinstall\\n' "$ENTRY" "$BIN" >&2
  exit 1
fi
exec "$BIN" "$@"
"""


def launcher_source(entry: str) -> str:
    """Return the stable shell launcher text for one maintained entry point.

    The ``lubko-supervisor`` entry uses a special launcher that checks for a
    temporary supervisor-runtime override before resolving through
    ``cli/current``.  All other entries resolve through ``cli/current`` only.

    The embedded state root is shell-quoted so a path containing a single
    quote cannot break the generated script.

    Args:
        entry: Maintained entry point name.

    Returns:
        Executable shell script resolving the active CLI commit.
    """
    escaped_root = str(state_root()).replace("'", "'\\''")
    if entry == SUPERVISOR_ENTRY:
        return _SUPERVISOR_LAUNCHER_TEMPLATE.replace(
            _SUPERVISOR_STATE_ROOT_PLACEHOLDER, escaped_root
        )
    return _LAUNCHER_TEMPLATE.format(state_root=escaped_root, entry=entry)


def install_launchers(bin_dir: Path) -> None:
    """Write every stable launcher into a bin directory.

    Each launcher is written atomically and never changed by deployments.

    Args:
        bin_dir: Directory to install the launchers into.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    for entry in ENTRY_POINTS:
        target = bin_dir / entry
        temporary = bin_dir / f"{entry}.tmp"
        temporary.write_text(launcher_source(entry), encoding="utf-8")
        temporary.chmod(0o755)
        temporary.replace(target)


def git_commit(repo: Path, timeout_seconds: float) -> str | None:
    """Return the full git commit of a checkout, read-only.

    Args:
        repo: Repository checkout to inspect.
        timeout_seconds: Bounded timeout.

    Returns:
        The full commit hash, or ``None`` when unavailable.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    commit = proc.stdout.strip()
    return commit or None
