"""Coherent resolution of the maintained Lubko command line tools.

The global entry points (``lubko-worker``, ``lubko-supervisor``, ``lubko-deploy``,
``lubko-deploy-ctl``, and ``lubko-install``) must always
resolve to code from the *confirmed* maintained commit. A supervised
deployment checks out a provisional candidate and may roll back to the
previous commit at any time before confirmation, so the global CLIs must never
be stranded on candidate code.

This module keeps the CLIs coherent with a stable indirection instead of
rewriting an installed ``uv`` tool in place:

- every global entry point is a small stable launcher script, written once by
  ``lubko-install`` and never rewritten by a deployment;
- each commit owns an immutable per-commit CLI environment under
  ``$XDG_STATE_HOME/lubko/cli/<commit>/``: a plain ``git archive`` extraction
  of the exact commit tree plus the virtualenv ``uv sync`` creates there; at
  materialization it is bound to the exact full commit by a manifest carrying
  a deterministic content digest, then ``sealed`` read-only — sealing never
  rewrites that identity, so normal operation never writes to it and a
  modified/re-sealed tree is never trusted;
- ``$XDG_STATE_HOME/lubko/cli/current`` is a symlink selecting the active
  commit and is switched with a single atomic ``os.replace``.

Deployments build the candidate environment during the provisional phase and
only move ``current`` after durable ``confirmed`` state exists. A rollback
therefore never needs to restore the CLIs: the pointer was never moved, so the
prior confirmed CLI version is preserved by construction.

A sealed runtime is only ever made writable again (``unseal_runtime``) for an
explicit rebuild/removal/GC operation; it is never unsealed during ordinary
start, restart, probe, or crash recovery.
"""

from __future__ import annotations

import hashlib
import io
import json
import os
import re
import shutil
import stat
import subprocess
import sys
import tarfile
from contextlib import suppress
from operator import itemgetter
from pathlib import Path
from typing import TYPE_CHECKING, Final

from lubko.durable import DurabilityError, write_symlink_durable
from lubko.state import cli_root_dir, state_root
from lubko.supervise import DesiredIntentError
from lubko.supervise_client import read_desired_client, read_state_client

if TYPE_CHECKING:
    from collections.abc import Sequence

ENTRY_POINTS: Final = (
    "lubko-worker",
    "lubko-supervisor",
    "lubko-deploy",
    "lubko-deploy-ctl",
    "lubko-install",
)
RETIRED_ENTRY_POINTS: Final = (
    "lubko-agent",
    "my-lubko-agent",
    "lubko-board",
)
"""Entry points removed from the maintained set but retained as inert compatibility names.

An already-deployed deploy controller or supervisor can validate each candidate
runtime against its own, larger entry-point set. Dropping a maintained entry
point without preserving its name therefore makes a newer runtime unbuildable
or unlaunchable for that predecessor.

Every retired name is installed by package metadata as an inert console script,
so even an old builder sees it immediately after ``uv sync`` and before that
builder runs its own completeness check. Fresh builders also keep the fallback
bridge materialization below. The compatibility entry points deliberately run
nothing; they exist only to keep supported predecessor requirement sets
satisfiable while the real maintained CLI surface remains smaller.
"""
CURRENT_LINK_NAME: Final = "current"
CURRENT_TMP_NAME: Final = "current.tmp"
DEFAULT_BUILD_TIMEOUT_SECONDS: Final = 600.0
UV_HTTP_TIMEOUT: Final = "30"

RUNTIME_MANIFEST_NAME: Final = "lubko-runtime.json"
RUNTIME_MANIFEST_SCHEMA: Final = 2
COMMIT_PATH_RE: Final = re.compile(r"[0-9a-fA-F]{40}")

_WRITE_BITS: Final = stat.S_IWUSR | stat.S_IWGRP | stat.S_IWOTH

_LAUNCHER_TEMPLATE: Final = """#!{sh}
# Stable Lubko launcher (generated by lubko-install). Deployments never rewrite
# this file; they only switch the `current` symlink that this script resolves.
set -u
LINK='{state_root}/cli/current'
ENTRY='{entry}'
if [ ! -L "$LINK" ]; then
  printf '%s: no maintained Lubko CLI; run lubko-install\\n' "$ENTRY" >&2
  exit 1
fi
BASE="$(dirname "$LINK")"
TARGET="$(readlink "$LINK")" || exit 1
case "$TARGET" in
  /*) REL="$TARGET" ;;
  *) REL="$BASE/$TARGET" ;;
esac
ROOT="$(cd "$REL" 2>/dev/null && pwd -P)" || {{
  printf '%s: maintained CLI root %s missing; reinstall\\n' "$ENTRY" "$REL" >&2
  exit 1
}}
BIN="$ROOT/.venv/bin/$ENTRY"
if [ ! -x "$BIN" ]; then
  printf '%s: incomplete CLI root (%s); reinstall\\n' "$ENTRY" "$BIN" >&2
  exit 1
fi
exec "$BIN" "$@"
"""

_BRIDGE_TEMPLATE: Final = """#!/bin/sh
# Retired Lubko entry point, bridged for supervisor upgrade compatibility.
printf '%s: this entry point was removed from the maintained CLIs.\\n' "{entry}" >&2
printf 'It is bridged only so an already-deployed supervisor can still validate\\n' >&2
printf 'and launch this runtime; use a maintained entry point instead.\\n' >&2
exit 127
"""




def retired_entry_point_main() -> int:
    """Refuse execution of a retired CLI name kept only for upgrade compatibility.

    Returns:
        Exit status 127, matching an unavailable command.
    """
    entry = Path(sys.argv[0]).name
    print(f"{entry}: this entry point was removed from the maintained CLIs.", file=sys.stderr)
    print(
        "It remains installed only so an older Lubko deployment can validate "
        "and upgrade to this runtime.",
        file=sys.stderr,
    )
    return 127

class CliError(RuntimeError):
    """Raised when a maintained CLI environment cannot be built or switched."""


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------


def is_valid_commit_name(name: str) -> bool:
    """Return whether ``name`` is exactly 40 hexadecimal characters.

    Runtime directories are addressed by the full commit SHA alone; a short
    ref, a relative path, or any non-hex value must never resolve to a runtime
    path.

    Args:
        name: Candidate commit name.

    Returns:
        ``True`` when the name is exactly 40 hex characters.
    """
    return COMMIT_PATH_RE.fullmatch(name) is not None


def validate_commit_name(commit: str) -> None:
    """Require ``commit`` to be exactly 40 hexadecimal characters.

    Args:
        commit: Exact commit hash.

    Raises:
        CliError: If the value is not a full 40-hex-character commit.
    """
    if not is_valid_commit_name(commit):
        msg = "runtime commits must be exactly 40 hexadecimal characters"
        raise CliError(msg)


def cli_commit_dir(commit: str) -> Path:
    """Return the immutable CLI environment directory of one commit.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        The per-commit CLI root.
    """
    validate_commit_name(commit)
    return cli_root_dir() / commit


def current_link_path() -> Path:
    """Return the symlink selecting the active maintained CLI commit.

    Returns:
        The ``current`` symlink path.
    """
    return cli_root_dir() / CURRENT_LINK_NAME


def current_commit() -> str | None:
    """Return the commit the maintained CLIs currently resolve to.

    Returns:
        The active commit, or ``None`` when no maintained CLI is active.
    """
    try:
        target = current_link_path().readlink()
    except OSError:
        return None
    return Path(target).name


def cli_entry_executable(commit: str, entry: str) -> Path | None:
    """Return the executable for an entry point within one commit root.

    Args:
        commit: Exact commit hash.
        entry: Maintained entry point name.

    Returns:
        The virtualenv entry-point script, or ``None`` when it is absent.
    """
    executable = cli_commit_dir(commit) / ".venv" / "bin" / entry
    if executable.is_file():
        return executable
    return None


def _root_is_usable(commit: str) -> bool:
    """Return whether a commit's CLI environment looks fully built.

    Every maintained entry point must exist: a root that predates one of them
    would leave that command broken for whoever resolves this runtime.

    Args:
        commit: Exact commit hash.

    Returns:
        ``True`` when the per-commit environment has every maintained entry
        point.
    """
    return all(cli_entry_executable(commit, entry) is not None for entry in ENTRY_POINTS)


def known_entry_points() -> frozenset[str]:
    """Return every entry point name any supported runtime may be asked for.

    Args:
        None.

    Returns:
        The maintained names plus the bridged retired names.
    """
    return frozenset(ENTRY_POINTS) | frozenset(RETIRED_ENTRY_POINTS)


def root_entry_points(commit: str) -> frozenset[str]:
    """Return the known entry points actually usable in one commit runtime.

    This is a capability probe of the runtime itself, never of what some
    caller declares: a name counts only when this module can resolve it as a
    usable entry point in the runtime's own virtualenv.

    The usability test lives in :func:`cli_entry_executable` alone and this
    probe is defined in terms of it, so the set of names a runtime reports and
    the set of names the rest of the module can actually resolve can never
    diverge. A disagreement here would be silent and severe: the runtime would
    pass the usability gate, be declared unusable for every upgrade, and never
    be retired. Executability proper is enforced where a launch really happens,
    by the launcher's own ``-x`` test.

    Args:
        commit: Exact commit hash.

    Returns:
        The entry points this runtime can really launch, empty when the root is
        missing or unreadable.
    """
    return frozenset(
        name for name in known_entry_points() if cli_entry_executable(commit, name) is not None
    )


def satisfies_entry_points(present: frozenset[str], required: frozenset[str]) -> bool:
    """Return whether a runner can satisfy every entry point a runtime requires.

    The relation is directional on purpose: a runner is compatible with a
    target when the runner provides at least everything the target declares.
    A runner with a strict superset of the target's requirements is therefore
    safe, while a target that would need something the runner lacks is not.
    The reverse question -- whether the target still satisfies a larger,
    older requirement set -- is answered by the target runtime bridging those
    names, never by comparing the two declared sets against each other.

    It fails closed: an empty or unknown side is never compatible.

    Args:
        present: Entry points a runner can actually launch.
        required: Entry points the runtime needs.

    Returns:
        ``True`` only when ``required`` is non-empty and fully covered.
    """
    if not present or not required:
        return False
    return required <= present


def runtime_satisfies(commit: str, required: frozenset[str]) -> bool:
    """Return whether one commit runtime can be launched by a given runner.

    A usable runtime is not enough on its own: the runner's own entry-point
    requirements must all be resolvable inside this runtime, so a runtime built
    by a newer tree stays launchable for an already-deployed predecessor whose
    requirement set is a superset of the maintained one.

    Args:
        commit: Exact commit hash of the runtime to launch.
        required: Entry points the running runner insists on.

    Returns:
        ``True`` only when the runtime is usable and provides ``required``.
    """
    return runtime_is_usable(commit) and satisfies_entry_points(root_entry_points(commit), required)


def manifest_path(commit: str) -> Path:
    """Return the binding-manifest path of one commit runtime.

    The manifest binds the materialized tree to the exact full commit, the
    runtime schema, and a deterministic content digest of the sealed tree so a
    stale, wrong-commit, partially built, or tampered tree can never be
    mistaken for the exact deployed runtime.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        The ``lubko-runtime.json`` path inside the commit runtime.
    """
    return cli_commit_dir(commit) / RUNTIME_MANIFEST_NAME


def _lstat_mode(path: Path) -> int | None:
    """Return the mode of a path without following a trailing symlink.

    Args:
        path: Path to inspect.

    Returns:
        The link-safe mode bits, or ``None`` when the entry is gone/unreadable.
    """
    try:
        return path.lstat().st_mode
    except OSError:
        return None


def _seal_tree(root: Path) -> None:
    """Remove every write bit below ``root`` so normal operation cannot modify it.

    Symlinks are never chmodded: mutating a symlink's mode bits would follow
    the link and alter an external target. Only regular files and directories
    are sealed.

    Args:
        root: Runtime tree to make read-only.
    """
    for dirpath, dirnames, filenames in os.walk(root):
        for name in (*dirnames, *filenames):
            with suppress(OSError):
                path = Path(dirpath) / name
                mode = path.lstat().st_mode
                if not stat.S_ISLNK(mode):
                    path.chmod(mode & ~_WRITE_BITS)
        with suppress(OSError):
            directory = Path(dirpath)
            mode = directory.lstat().st_mode
            if not stat.S_ISLNK(mode):
                directory.chmod(mode & ~_WRITE_BITS)


def _unseal_tree(root: Path) -> None:
    """Restore owner-write permission below ``root`` for a rebuild/removal/GC.

    Symlinks are deliberately skipped: only regular files and directories are
    made writable, so an external symlink target retains its own mode.

    Args:
        root: Runtime tree to make writable again.
    """
    for dirpath, dirnames, filenames in os.walk(root):
        for name in (*dirnames, *filenames):
            with suppress(OSError):
                path = Path(dirpath) / name
                mode = path.lstat().st_mode
                if not stat.S_ISLNK(mode):
                    path.chmod(mode | stat.S_IWUSR)
        with suppress(OSError):
            directory = Path(dirpath)
            mode = directory.lstat().st_mode
            if not stat.S_ISLNK(mode):
                directory.chmod(mode | stat.S_IWUSR)


def _tree_is_read_only(root: Path) -> bool:
    """Return whether every entry below ``root`` is free of write bits.

    Symlinks are inspected with ``lstat`` and excluded from the write-bit
    rule: their mode bits cannot escape the sealed runtime because sealing
    never follows a symlink, and ``os.walk`` does not descend into symlinked
    directories.

    Args:
        root: Runtime tree to verify.

    Returns:
        ``True`` when no regular file or directory under ``root`` is writable.
    """
    if not root.is_dir():
        return False
    for dirpath, dirnames, filenames in os.walk(root):
        for name in (*dirnames, *filenames):
            mode = _lstat_mode(Path(dirpath) / name)
            if mode is None:
                return False
            if stat.S_ISLNK(mode):
                continue
            if mode & _WRITE_BITS:
                return False
        mode = _lstat_mode(Path(dirpath))
        if mode is None or mode & _WRITE_BITS:
            return False
    return True


def _file_content_digest(path: Path) -> bytes:
    """Return the raw SHA-256 of one regular file's contents.

    Args:
        path: Regular file to digest.

    Returns:
        The 32 raw digest bytes.
    """
    hasher = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(1024 * 1024)
            if not chunk:
                return hasher.digest()
            hasher.update(chunk)


def _runtime_content_digest(root: Path) -> bytes:
    """Return the deterministic content digest of one runtime tree.

    The digest binds every entry below ``root`` except the binding manifest
    itself: regular files contribute their relative path, permission mode
    (write bits masked so sealing order never matters), and a content digest;
    symlinks contribute their relative path and exact link target without ever
    following the link; directories and any other entry type contribute their
    relative path (and mode where meaningful). Each contribution is
    length-prefixed, so added, removed, renamed, or tampered entries always
    change the digest.

    Args:
        root: Runtime tree to digest.

    Returns:
        The raw SHA-256 digest bytes over the canonical tree encoding.
    """
    root_s = os.fspath(root)
    entries: list[tuple[str, str, os.stat_result]] = []

    def _collect(directory: str, prefix: str) -> None:
        with os.scandir(directory) as iterator:
            for entry in iterator:
                name = entry.name
                if not prefix and name == RUNTIME_MANIFEST_NAME:
                    continue
                rel = f"{prefix}{name}" if not prefix else f"{prefix}/{name}"
                # Pure-string hot path: avoid Path overhead in digest loop.
                full = os.path.join(directory, name)  # ruff: ignore[os-path-join]
                info = os.lstat(full)
                entries.append((rel, full, info))
                if stat.S_ISDIR(info.st_mode):
                    _collect(full, rel)

    _collect(root_s, "")
    entries.sort(key=itemgetter(0))
    hasher = hashlib.sha256()

    def update(data: bytes) -> None:
        hasher.update(len(data).to_bytes(8, "big"))
        hasher.update(data)

    for rel, full, info in entries:
        update(rel.encode("utf-8"))
        if stat.S_ISREG(info.st_mode):
            update(b"f")
            update((info.st_mode & ~_WRITE_BITS & 0o777).to_bytes(2, "big"))
            update(_file_content_digest(Path(full)))
        elif stat.S_ISLNK(info.st_mode):
            update(b"l")
            # Pure-string hot path: avoid Path overhead in digest loop.
            update(os.fspath(os.readlink(full)).encode("utf-8"))  # ruff: ignore[os-readlink]
        elif stat.S_ISDIR(info.st_mode):
            update(b"d")
        else:
            update(b"o")
            update((info.st_mode & ~_WRITE_BITS & 0o777).to_bytes(2, "big"))

    return hasher.digest()


def _write_runtime_manifest(commit: str) -> None:
    """Bind one materialized runtime to its exact commit with a content digest.

    The expected identity of a commit runtime is established exactly once, at
    materialization time, from the tree just extracted from the exact commit
    (``git archive`` plus ``uv sync``). Sealing later only changes permissions
    and never rewrites this manifest, so a tree modified after materialization
    can never be re-blessed while still claiming ``commit``.

    Args:
        commit: Exact 40-character commit hash.

    Raises:
        CliError: If the runtime tree cannot be digested.
    """
    root = cli_commit_dir(commit)
    try:
        content_digest = _runtime_content_digest(root).hex()
    except OSError as exc:
        msg = f"could not digest the runtime tree for commit {commit}: {exc}"
        raise CliError(msg) from exc
    manifest = {
        "schema_version": RUNTIME_MANIFEST_SCHEMA,
        "commit": commit,
        "content_digest": content_digest,
    }
    manifest_path(commit).write_text(json.dumps(manifest, sort_keys=True) + "\n", encoding="utf-8")


def seal_runtime(commit: str) -> None:
    """Seal one materialized commit runtime read-only.

    Only permission bits below the runtime tree are removed: the integrity
    manifest is written at materialization time and is never rewritten here, so
    a later unseal/reseal cannot redefine the commit-bound expected identity.
    Normal operation (start, restart, probe, crash recovery) must only ever use
    a sealed runtime whose manifest is verified. Symlinks in the tree are never
    followed or chmodded.

    Args:
        commit: Exact 40-character commit hash to seal.
    """
    validate_commit_name(commit)
    root = cli_commit_dir(commit)
    if not root.is_dir():
        return
    _seal_tree(root)


def unseal_runtime(commit: str) -> None:
    """Make a sealed commit runtime writable for an explicit rebuild/removal/GC.

    This is the deliberate, supported exception to read-only operation. It is
    only invoked by operations that repair or remove the tree; ordinary
    supervised start/restart never unseals. Symlinks in the tree are never
    followed or chmodded.

    Args:
        commit: Exact 40-character commit hash to unseal.
    """
    validate_commit_name(commit)
    root = cli_commit_dir(commit)
    if root.is_dir():
        _unseal_tree(root)


def _manifest_digest(data: object, commit: str) -> bytes | None:
    """Return the tree digest recorded by a manifest when it binds ``commit``.

    Args:
        data: Parsed manifest document.
        commit: Exact commit the manifest must bind.

    Returns:
        The recorded content-digest bytes, or ``None`` when the manifest does
        not bind ``commit`` under the current schema or carries no valid digest.
    """
    if not (
        isinstance(data, dict)
        and data.get("schema_version") == RUNTIME_MANIFEST_SCHEMA
        and data.get("commit") == commit
    ):
        return None
    expected = data.get("content_digest")
    if not isinstance(expected, str):
        return None
    try:
        return bytes.fromhex(expected)
    except ValueError:
        return None


def runtime_is_usable(commit: str) -> bool:  # ruff: ignore[too-many-return-statements]
    """Return whether a commit runtime is complete, exactly bound, and sealed.

    An incomplete, wrong-commit, corrupt, or content-tampered tree is
    deliberately reported unusable so callers fail closed instead of launching
    arbitrary mutable code. The manifest's ``content_digest`` is recomputed over
    the current tree on every call, so a runtime that was unsealed, modified,
    and re-sealed without regenerating the manifest is rejected. An invalid
    commit name is never usable.

    Args:
        commit: Exact 40-character commit hash.

    Returns:
        ``True`` only when every entry point exists, the manifest binds the
        tree to ``commit`` under the current schema, the tree is read-only, and
        the recomputed tree digest matches the manifest.
    """
    if not is_valid_commit_name(commit) or not _root_is_usable(commit):
        return False
    try:
        data = json.loads(manifest_path(commit).read_text())
    except (OSError, ValueError):
        return False
    expected = _manifest_digest(data, commit)
    if expected is None:
        return False
    root = cli_commit_dir(commit)
    try:
        if _runtime_content_digest(root) != expected:
            return False
    except OSError:
        return False
    if _tree_is_read_only(root):
        return True
    # `cli/current` is the independently confirmed recovery anchor.  A failed
    # deployment may have left its permission bits writable without changing
    # any manifest-bound content.  In that exact case, restore the seal in
    # place instead of treating the already-proven runtime as disposable.
    # Candidate runtimes never get this privilege, and modified content was
    # rejected above before any chmod occurs.
    if current_commit() != commit:
        return False
    seal_runtime(commit)
    if not _tree_is_read_only(root):
        return False
    try:
        return _runtime_content_digest(root) == expected
    except OSError:
        return False


# ---------------------------------------------------------------------------
# Build and activation
# ---------------------------------------------------------------------------


def _extract_archive(repo: Path, commit: str, destination: Path, timeout_seconds: float) -> None:
    """Extract the exact tree of a commit into a directory.

    Args:
        repo: Repository checkout that contains the commit.
        commit: Exact commit hash to extract.
        destination: Directory to receive the extracted tree.
        timeout_seconds: Bounded timeout for creating the Git archive.

    Raises:
        CliError: If the archive or extraction fails.
    """
    try:
        archived = subprocess.run(
            ["git", "-C", str(repo), "archive", commit],
            capture_output=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not archive commit {commit}: {exc}"
        raise CliError(msg) from exc
    if archived.returncode != 0:
        detail = (
            archived.stderr or archived.stdout
        ).decode().strip() or f"exit code {archived.returncode}"
        msg = f"git archive of commit {commit} failed: {detail}"
        raise CliError(msg)
    try:
        with tarfile.open(fileobj=io.BytesIO(archived.stdout), mode="r:") as archive:
            archive.extractall(destination, filter="data")
    except (OSError, tarfile.TarError) as exc:
        msg = f"could not extract commit {commit}: {exc}"
        raise CliError(msg) from exc


def _sync_venv(uv_path: str, root: Path, timeout_seconds: float) -> None:
    """Synchronize the virtualenv of one extracted commit tree.

    Args:
        uv_path: Path to the ``uv`` executable.
        root: Extracted commit tree.
        timeout_seconds: Bounded timeout.

    Raises:
        CliError: If ``uv sync`` fails.
    """
    env = dict(os.environ)
    env.setdefault("UV_HTTP_TIMEOUT", UV_HTTP_TIMEOUT)
    try:
        proc = subprocess.run(
            [uv_path, "sync", "--frozen", "--project", str(root)],
            cwd=root,
            env=env,
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        msg = f"could not synchronize the CLI environment: {exc}"
        raise CliError(msg) from exc
    if proc.returncode != 0:
        lines = [line for line in (proc.stderr or proc.stdout).splitlines() if line]
        detail = "\n".join(lines[-10:]) or f"exit code {proc.returncode}"
        msg = f"uv sync for the CLI environment failed:\n{detail}"
        raise CliError(msg)


def install_entry_point_bridges(commit: str) -> None:
    """Bridge every retired entry point missing from one freshly built runtime.

    Retired names are normally installed by package metadata during ``uv sync``
    so even a predecessor builder sees them before its own completeness check.
    This post-sync materialization is defense in depth for fresh builders and
    runs before the binding manifest is written, so any fallback bridge is part
    of the manifest-bound content identity.

    A name that already exists is left untouched: package-installed
    compatibility scripts and any real entry point always win.

    Args:
        commit: Exact commit hash of the runtime being built.

    Raises:
        CliError: If a bridge script cannot be materialized.
    """
    bin_dir = cli_commit_dir(commit) / ".venv" / "bin"
    for entry in RETIRED_ENTRY_POINTS:
        script = bin_dir / entry
        if script.exists():
            continue
        try:
            script.write_text(_BRIDGE_TEMPLATE.format(entry=entry), encoding="utf-8")
            script.chmod(0o755)
        except OSError as exc:
            msg = f"could not bridge the retired entry point {entry} for commit {commit}: {exc}"
            raise CliError(msg) from exc


def build_cli_root(repo: Path, commit: str, uv_path: str, timeout_seconds: float) -> Path:
    """Build or reuse the immutable CLI environment for one exact commit.

    The environment is extracted with ``git archive`` and synchronized with
    ``uv sync`` directly at its final location, so entry-point shebangs stay
    valid, and the retired entry points are bridged in before the tree is
    manifest-bound and sealed. Building the same commit twice is idempotent and
    never rewrites an already-sealed usable environment. Once materialized and
    verified it is sealed read-only; an unsealed/corrupt/wrong-commit tree is
    unsealed, removed, and rebuilt rather than trusted.

    Args:
        repo: Repository checkout that contains the commit.
        commit: Exact commit hash.
        uv_path: Path to the ``uv`` executable.
        timeout_seconds: Bounded timeout per step.

    Returns:
        The commit's sealed CLI environment directory.

    Raises:
        CliError: If the environment cannot be built or sealed.
    """
    validate_commit_name(commit)
    destination = cli_commit_dir(commit)
    if runtime_is_usable(commit):
        return destination
    if current_commit() == commit:
        msg = (
            f"refusing to rebuild confirmed CLI environment for commit {commit}; "
            "its manifest-bound content identity could not be restored"
        )
        raise CliError(msg)
    unseal_runtime(commit)
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)
    try:
        _extract_archive(repo, commit, destination, timeout_seconds)
        _sync_venv(uv_path, destination, timeout_seconds)
    except CliError:
        shutil.rmtree(destination, ignore_errors=True)
        raise
    if not _root_is_usable(commit):
        shutil.rmtree(destination, ignore_errors=True)
        msg = f"CLI environment for commit {commit} is incomplete after build"
        raise CliError(msg)
    install_entry_point_bridges(commit)
    _write_runtime_manifest(commit)
    seal_runtime(commit)
    if not runtime_is_usable(commit):
        unseal_runtime(commit)
        shutil.rmtree(destination, ignore_errors=True)
        msg = f"CLI environment for commit {commit} could not be sealed"
        raise CliError(msg)
    return destination


def set_current(commit: str) -> None:
    """Crash-durably select the commit the maintained CLIs resolve to.

    ``cli/current`` is recovery authority for the maintained CLI environment:
    every maintained command resolves through it, so the symlink switch must be
    confirmed durable before the activation is reported as successful.

    Args:
        commit: Exact commit hash to activate.

    Raises:
        CliError: If the pointer cannot be switched or ``commit`` is invalid.
    """
    validate_commit_name(commit)
    try:
        write_symlink_durable(current_link_path(), commit)
    except DurabilityError as exc:
        msg = f"could not activate CLI commit {commit}: {exc}"
        raise CliError(msg) from exc


def reconcile_pointer(commit: str) -> bool:
    """Idempotently repair the active pointer so it selects one commit.

    The switch happens only when the commit's environment is already sealed and
    usable, so a repair never activates an incomplete, unsealed, corrupt, or
    wrong-commit root and never touches a provisional candidate that is not
    yet the confirmed commit. An already-current pointer is only blessed when
    the runtime it points to is itself usable.

    Args:
        commit: Exact commit hash the pointer should select.

    Returns:
        ``True`` when the pointer now selects a usable runtime (there was
        nothing to repair, or the repair succeeded), ``False`` when the
        runtime is missing, unusable, invalid, or the pointer could not be
        switched.
    """
    if not runtime_is_usable(commit):
        return False
    if current_commit() == commit:
        return True
    try:
        set_current(commit)
    except CliError:
        return False
    return True


def supervisor_authoritative_commits() -> set[str]:
    """Return every runtime commit the supervisor may still rely on.

    The union covers:
    - the durable desired intent (worker target commit);
    - the daemon's applied state commit;
    - the supervisor's own runtime commit (the code the supervisor is
      executing from, which may differ from the worker commit after a
      deployment).

    All three can name a runtime the supervisor daemon or its maintained
    worker must still be able to start (including on restart and during
    spawned two-phase handoff), so garbage collection must never delete them —
    even when they are absent from an explicit keep list.

    Returns:
        The set of valid 40-hex commits that must be preserved.
    """
    preserved: set[str] = set()
    try:
        desired = read_desired_client()
    except (DesiredIntentError, ConnectionError, OSError):
        desired = None
    if desired is not None and is_valid_commit_name(desired.commit):
        preserved.add(desired.commit)
    try:
        state = read_state_client()
    except (ConnectionError, OSError):
        return preserved
    state_commit = state.commit
    if state_commit is not None and is_valid_commit_name(state_commit):
        preserved.add(state_commit)
    # The supervisor's own runtime must never be garbage-collected while
    # the supervisor is still executing from it (before a successful
    # spawned two-phase handoff).
    sr_commit = state.supervisor_runtime_commit
    if sr_commit is not None and is_valid_commit_name(sr_commit):
        preserved.add(sr_commit)
    return preserved


def remove_cli_root(commit: str) -> None:
    """Remove one commit's CLI environment if it is not authoritative.

    A sealed runtime is unsealed first so the explicit removal actually works.
    An invalid commit name is never removed, and neither is any
    supervisor-authoritative commit (desired intent or applied state): deleting a
    runtime the supervisor may still start would create
    worker/CLI divergence and a later outage (fail closed).

    Args:
        commit: Exact commit hash to remove.
    """
    if not is_valid_commit_name(commit) or commit == current_commit():
        return
    if commit in supervisor_authoritative_commits():
        return
    root = cli_commit_dir(commit)
    if not root.exists():
        return
    unseal_runtime(commit)
    shutil.rmtree(root, ignore_errors=True)


def gc_cli_roots(keep: Sequence[str]) -> None:
    """Remove every CLI environment except the commits listed.

    The environment selected by the ``current`` symlink is always preserved,
    even when it is absent from ``keep``. Activation may have failed after
    durable state was written, so a cleanup must never delete the root that the
    global CLIs currently resolve to. Every supervisor-authoritative runtime
    (desired intent or applied state) is also
    preserved: deleting a runtime the supervisor or its maintained worker may
    still start would create worker/CLI divergence and a later outage.
    Sealed environments are unsealed first so the explicit GC actually removes
    them; commit-addressed paths are validated before any unseal.

    Args:
        keep: Commits whose environments must be retained.
    """
    keep_set = set(keep)
    current = current_commit()
    if current is not None:
        keep_set.add(current)
    keep_set.update(supervisor_authoritative_commits())
    for path in cli_root_dir().iterdir() if cli_root_dir().is_dir() else ():
        if path.name in {CURRENT_LINK_NAME, CURRENT_TMP_NAME}:
            continue
        if path.name not in keep_set:
            if is_valid_commit_name(path.name):
                unseal_runtime(path.name)
            shutil.rmtree(path, ignore_errors=True)


# ---------------------------------------------------------------------------
# Launchers
# ---------------------------------------------------------------------------


def launcher_source(entry: str) -> str:
    """Return stable launcher text resolving only through ``cli/current``.

    ``cli/current`` is the independently confirmed recovery anchor. No entry
    point, including ``lubko-supervisor``, has a second runtime-selection path.

    The shebang resolves the ``sh`` executable at generation time so generated
    launchers are directly executable on both GNU Linux (``/bin/sh``) and
    Termux (``/data/data/com.termux/files/usr/bin/sh``).

    Args:
        entry: Maintained entry point name.

    Returns:
        Executable shell script resolving the confirmed CLI commit.

    Raises:
        CliError: If ``sh`` is not found on PATH.
    """
    sh = shutil.which("sh")
    if sh is None:
        msg = "sh not found on PATH; a POSIX shell is required to generate launchers"
        raise CliError(msg)
    escaped_root = str(state_root()).replace("'", "'\\''")
    return _LAUNCHER_TEMPLATE.format(sh=sh, state_root=escaped_root, entry=entry)


def install_launchers(bin_dir: Path) -> None:
    """Write every stable launcher into a bin directory.

    Each launcher is written atomically and never changed by deployments. A
    launcher whose installed bytes and executable mode already match the
    generated source is left untouched, so reinstalling an already-valid
    deployment performs no persistent-filesystem writes at all.

    Args:
        bin_dir: Directory to install the launchers into.
    """
    bin_dir.mkdir(parents=True, exist_ok=True)
    for entry in ENTRY_POINTS:
        target = bin_dir / entry
        expected = launcher_source(entry)
        if _launcher_current(target, expected):
            continue
        temporary = bin_dir / f"{entry}.tmp"
        temporary.write_text(expected, encoding="utf-8")
        temporary.chmod(0o755)
        temporary.replace(target)


def _launcher_current(target: Path, expected: str) -> bool:
    """Return whether an installed launcher already matches the source.

    Args:
        target: Installed launcher path.
        expected: Generated launcher source.

    Returns:
        ``True`` only when the launcher exists as a regular file, is
        executable, and carries exactly the expected bytes. Reads only.
    """
    try:
        if target.is_symlink() or not target.is_file():
            return False
        if not os.access(target, os.X_OK):
            return False
        return target.read_text(encoding="utf-8") == expected
    except OSError:
        return False


def git_commit(repo: Path, timeout_seconds: float) -> str | None:
    """Return the full git commit of a checkout, read-only.

    Args:
        repo: Repository checkout to inspect.
        timeout_seconds: Bounded timeout.

    Returns:
        The full commit hash, or ``None`` when unavailable.
    """
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo), "rev-parse", "HEAD"],
            capture_output=True,
            text=True,
            timeout=timeout_seconds,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if proc.returncode != 0:
        return None
    commit = proc.stdout.strip()
    return commit or None
